### ISSUE TITLE
Improve installation guide 

### ISSUE THREAD

**Issue by dhensby** [kinglozzer/silverstripe-metatitle#4]
It would be useful to provide more in depth installation instructions. 

Such as template changes needed (if any) or how to install without composer. 

Usage guide would be good too. I think a lot of 3.0 knowledge is assumed, which is not always the case

**Comment by kinglozzer** [comment]
I’ve pushed some more detailed instructions, let me know if you think anything is missing :)

**Comment by dhensby** [comment]
Looks good, thanks :_
