### ISSUE TITLE
Fatal error: Call to undefined method SilverStripe\Forms\FormField::create_tag()

### ISSUE THREAD

**Issue by thats4shaw** [kinglozzer/silverstripe-metatitle#9]
Installed 2.0.0 on SilverStripe 4.0.0-beta1. 

Fatal error: Call to undefined method SilverStripe\Forms\FormField::create_tag() in /metatitle/code/MetaTitleExtension.php on line 69.

Occurs only on index of the site.

Side effect of this: https://github.com/silverstripe/silverstripe-framework/commit/64e802f7955df2738d6d7381d30843f0cd438332.

**Comment by kinglozzer** [comment]
Thanks @thats4shaw, I’ve tagged `2.0.1` with a fix
